#!/usr/bin/env bash
# Install nginx web server
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

new_str="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUl\
wu4 permanent;"
sudo sed -i "42i $new_str" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404
new_str="\\\terror_page 404 /error404;"
sudo sed -i "43i $new_str" /etc/nginx/sites-available/default
sudo service nginx restart
