#!/usr/bin/env bash
#Install LB
sudo apt update
sudo apt -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt update
sudo apt install -y haproxy=2.0.\*
lb_config="\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 38194-web-01 100.26.253.17:80 check\n\tserver 38194-web-02 54.237.62.170:80 check\n"
echo -e "$lb_config" | sudo tee --append /etc/haproxy/haproxy.cfg
sudo service haproxy restart
