#!/usr/bin/env bash
# Clock
hour=1
echo "Hour: 0"
while [ $hour -le 13 ]; do
    min=1
    while [ $min -le 60 ]; do
		if [ $min == 60 ]; then
			if [ $hour != 13 ]; then
				echo "Hour: $hour"
			fi
		else
			echo "$min"
		fi
		min=$((min + 1))
    done
    hour=$((hour + 1))
done
